trigger:
- master

pr:
- master
 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Scan
    displayName: Scan
    jobs:
      - job: plan
        pool:
          vmImage: ubuntu-latest
        displayName: Checkov scan
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.3'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              pip install checkov
              sudo npm install -g aws-cdk
          displayName: Install cdk and checkov
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: $(System.DefaultWorkingDirectory)            
            script: |
              pip install -r requirements.txt
              cdk synth
              checkov -f cdk.out/cdkgoat.template.json -o junitxml > Checkov-Report.xml'
          continueOnError: true
          displayName: Checkov scan
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            searchFolder: '$(System.DefaultWorkingDirectory)'
            testResultsFiles: '**/*Checkov-Report.xml'
            mergeTestResults: false
            testRunTitle: Checkov Dev workspace scan
            failTaskOnFailedTests: false
            publishRunAttachments: true
          displayName: Publish Test Result
